import type { MenuItem } from "./types";

// Mock data simulating GET /api/menu response
// Will be replaced with actual API calls when backend is connected
export const mockMenuItems: MenuItem[] = [
  // Mon chinh
  {
    id: 1,
    name: "Com Ga Xoi Mo",
    category: "Mon chinh",
    price: 45000,
    description: "Ga ta chon loc, xoi mo vang gion, com dau thom ngat. Kem nuoc mam dac biet.",
    imageUrl: "https://picsum.photos/seed/comga-xoimo/600/400",
    isAvailable: true,
    stockCount: 50,
  },
  {
    id: 2,
    name: "Com Ga Luoc",
    category: "Mon chinh",
    price: 40000,
    description: "Ga luoc da vang, thit mem ngot tu nhien. Cham muoi tieu chanh.",
    imageUrl: "https://picsum.photos/seed/comga-luoc/600/400",
    isAvailable: true,
    stockCount: 30,
  },
  {
    id: 3,
    name: "Com Ga Quay",
    category: "Mon chinh",
    price: 50000,
    description: "Ga quay lu, da gion rum, thit thom dam da. Mon dac biet cua quan.",
    imageUrl: "https://picsum.photos/seed/comga-quay/600/400",
    isAvailable: true,
    stockCount: 20,
  },
  {
    id: 4,
    name: "Com Ga Sot Tieu",
    category: "Mon chinh",
    price: 48000,
    description: "Ga chien gion sot tieu den thom nong. An kem com trang va rau song.",
    imageUrl: "https://picsum.photos/seed/comga-sottieu/600/400",
    isAvailable: true,
    stockCount: 25,
  },
  {
    id: 5,
    name: "Com Ga Xa Ot",
    category: "Mon chinh",
    price: 48000,
    description: "Ga xao xa ot cay nhe, thom mui xa. Phu hop nguoi thich vi cay.",
    imageUrl: "https://picsum.photos/seed/comga-xaot/600/400",
    isAvailable: false,
    stockCount: 0,
  },

  // Mon them
  {
    id: 6,
    name: "Ga Chien Gion (Phan nho)",
    category: "Mon them",
    price: 25000,
    description: "Ga chien gion phan nho, thich hop an them.",
    imageUrl: "https://picsum.photos/seed/gachien-nho/600/400",
    isAvailable: true,
    stockCount: 40,
  },
  {
    id: 7,
    name: "Canh Ga Ham",
    category: "Mon them",
    price: 20000,
    description: "Canh ga ham rau cu, ngot nuoc tu nhien.",
    imageUrl: "https://picsum.photos/seed/canhga/600/400",
    isAvailable: true,
    stockCount: 15,
  },
  {
    id: 8,
    name: "Goi Ga",
    category: "Mon them",
    price: 30000,
    description: "Goi ga tron hanh tay, rau ram, dau phong. Chua ngot hap dan.",
    imageUrl: "https://picsum.photos/seed/goiga/600/400",
    isAvailable: true,
    stockCount: 20,
  },

  // Do uong
  {
    id: 9,
    name: "Tra Da",
    category: "Do uong",
    price: 5000,
    description: null,
    imageUrl: "https://picsum.photos/seed/trada/600/400",
    isAvailable: true,
    stockCount: 100,
  },
  {
    id: 10,
    name: "Nuoc Ngot",
    category: "Do uong",
    price: 12000,
    description: "Coca-Cola, Pepsi, 7Up, Fanta.",
    imageUrl: "https://picsum.photos/seed/nuocngot/600/400",
    isAvailable: true,
    stockCount: 60,
  },
  {
    id: 11,
    name: "Nuoc Chanh Tuoi",
    category: "Do uong",
    price: 15000,
    description: "Nuoc chanh tuoi vat, it duong. Mat lanh giai khat.",
    imageUrl: "https://picsum.photos/seed/nuocchanh/600/400",
    isAvailable: true,
    stockCount: 30,
  },
  {
    id: 12,
    name: "Nuoc Dua Tuoi",
    category: "Do uong",
    price: 18000,
    description: "Nuoc dua tuoi nguyen chat, mat lanh.",
    imageUrl: "https://picsum.photos/seed/nuocdua/600/400",
    isAvailable: false,
    stockCount: 0,
  },
];
